// Generated by Wrangler on Fri Sep 20 2024 15:00:15 GMT-0400 (Guyana Time)
// by running `wrangler types`

interface Env {
	GAME: DurableObjectNamespace<import("./src/index").Game>;
	TEAM: DurableObjectNamespace<import("./src/index").Team>;
	AI: Ai;
}
